### ISSUE TITLE
Scale-able GUI Doesn't Scale Font

### ISSUE THREAD

**Issue by b34st80y** [b34st80y/Hermes-Tracker#10]

**Comment by b34st80y** [comment]
Ok but should the font really need to change? The font doesn't change when you resize a chrome window or an explorer window...  Thoughts?

**Comment by Gervonte** [comment]
> Ok but should the font really need to change? The font doesn't change when you resize a chrome window or an explorer window... Thoughts?

That is true so maybe the base size for the font should be bigger instead.
